export const COMPANY = {
  name: "Kilimanjaro True Venture",
  tagline: "Experience True Adventure in Africa",
  email: "info@kilimanjarotrueventure.com",
  phone: "+255 123 456 789",
  whatsapp: "+255 123 456 789",
  address: "Sekei, Arusha, Tanzania",
  social: {
    instagram: "https://instagram.com/kilimanjarotrueventure",
    facebook: "https://facebook.com/kilimanjarotrueventure",
    tripadvisor: "https://tripadvisor.com/kilimanjarotrueventure",
  },
};

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  {
    label: "Tours",
    href: "/tours/kilimanjaro",
    children: [
      { label: "Mount Kilimanjaro", href: "/tours/kilimanjaro" },
      { label: "Mount Meru", href: "/tours/meru" },
      { label: "Wildlife Safaris", href: "/tours/safaris" },
      { label: "Zanzibar Holidays", href: "/tours/zanzibar" },
      { label: "Cultural Experiences", href: "/tours/cultural" },
    ],
  },
  { label: "Contact Us", href: "/contact" },
];

export const FEATURED_TOURS = [
  {
    title: "Mount Kilimanjaro",
    description:
      "Conquer Africa's highest peak via 6 unique routes. An unforgettable journey to the Roof of Africa at 5,895m.",
    href: "/tours/kilimanjaro",
    image: "/images/kilimanjaro-peak.jpg",
    tag: "Most Popular",
  },
  {
    title: "Mount Meru",
    description:
      "Tanzania's second-highest peak offers stunning views and incredible wildlife encounters on the trail.",
    href: "/tours/meru",
    image: "/images/guide-mountain.jpg",
    tag: "Hidden Gem",
  },
  {
    title: "Wildlife Safaris",
    description:
      "Witness the Big Five in Serengeti, Ngorongoro Crater, and Tarangire — Africa's iconic wildlife parks.",
    href: "/tours/safaris",
    image: "/images/zebra-herd.jpg",
    tag: "Adventure",
  },
  {
    title: "Zanzibar Holidays",
    description:
      "Relax in beautiful Zanzibar after your adventure. Crystal waters, Stone Town, and tropical paradise.",
    href: "/tours/zanzibar",
    image: "/images/flamingos-flight.jpg",
    tag: "Beach & Culture",
  },
  {
    title: "Cultural Experiences",
    description:
      "Immerse yourself in authentic Tanzanian culture with community visits, local traditions, and unique encounters.",
    href: "/tours/cultural",
    image: "/images/guide-client.jpg",
    tag: "Unique",
  },
];

export const KILIMANJARO_ROUTES = [
  {
    name: "Machame",
    nickname: "The Whiskey Route",
    durations: [
      { days: "7 Days", price: "From $2,130" },
      { days: "6 Days", price: "From $2,050" },
    ],
    difficulty: "Challenging",
    scenery: 5,
    description:
      'Known as the "Whiskey Route," Machame offers stunning scenery and strong acclimatization. Best for adventurous trekkers seeking scenic diversity.',
    itinerary: [
      "Hotel to Machame Gate – Machame Camp",
      "Machame Camp – Shira Camp",
      "Shira – Lava Tower – Barranco Camp",
      "Barranco – Karanga Camp",
      "Karanga – Barafu Camp",
      "Summit (Uhuru Peak) – Mweka Camp",
      "Mweka Camp – Mweka Gate (to hotel)",
    ],
    detailedItinerary: [
      {
        day: 1,
        title: "Machame Gate to Machame Camp",
        elevation: "1,800m to 3,000m",
        distance: "11 km",
        time: "5-7 hours",
        terrain: "Rainforest",
        description: "Your adventure begins with a drive from your hotel to Machame Gate (1,800m), where you'll register and meet your mountain crew. The trail winds through lush montane rainforest alive with birdsong, colobus monkeys, and towering moss-draped trees. The air is thick and humid as you climb steadily through the canopy, catching glimpses of sunlight filtering through the leaves. You'll arrive at Machame Camp nestled in a clearing at the edge of the forest.",
      },
      {
        day: 2,
        title: "Machame Camp to Shira Camp",
        elevation: "3,000m to 3,840m",
        distance: "5 km",
        time: "4-6 hours",
        terrain: "Moorland",
        description: "Leaving the rainforest behind, you emerge into the heath and moorland zone — a dramatic shift in landscape. Giant heather and wildflowers line the trail as the views open up spectacularly. On clear days, you'll catch your first breathtaking glimpse of Kibo peak towering above. The terrain becomes rocky and exposed as you cross the Shira Plateau, one of Kilimanjaro's ancient volcanic calderas.",
      },
      {
        day: 3,
        title: "Shira Camp to Lava Tower to Barranco Camp",
        elevation: "3,840m to 4,630m, descend to 3,960m",
        distance: "10 km",
        time: "6-8 hours",
        terrain: "Alpine desert",
        description: "Today follows the crucial \"climb high, sleep low\" principle. You'll ascend through the alpine desert to the imposing Lava Tower — a 90-metre volcanic rock formation at 4,630m. This is your first real test at altitude. After lunch in the shadow of the tower, you descend steeply into the stunning Barranco Valley. The descent aids acclimatization and you'll sleep over 600m lower than your high point, waking refreshed and better adapted.",
      },
      {
        day: 4,
        title: "Barranco Camp to Karanga Camp",
        elevation: "3,960m to 3,995m",
        distance: "5 km",
        time: "4-5 hours",
        terrain: "Rocky scramble & valley",
        description: "The day begins with the legendary Barranco Wall — a thrilling scramble up a near-vertical rock face. It looks intimidating but requires no technical climbing, just hands and feet and a sense of adventure. Your guides will be right beside you. From the top, you're rewarded with sweeping views of the southern glaciers and the summit. The trail then dips in and out of valleys before reaching Karanga Camp, your last water collection point.",
      },
      {
        day: 5,
        title: "Karanga Camp to Barafu Camp",
        elevation: "3,995m to 4,673m",
        distance: "4 km",
        time: "3-4 hours",
        terrain: "Barren alpine desert",
        description: "A shorter day designed to conserve energy for summit night. The trail crosses a barren, rocky landscape where very little grows — you're now in the true alpine desert. The air is thin and cold, and the summit feels tantalizingly close. You'll arrive at Barafu Camp (\"ice\" in Swahili) by early afternoon, giving you time to rest, eat, hydrate, and prepare mentally for the midnight summit push.",
      },
      {
        day: 6,
        title: "Summit Day — Uhuru Peak to Mweka Camp",
        elevation: "4,673m to 5,895m, descend to 3,068m",
        distance: "13 km",
        time: "12-16 hours",
        terrain: "Scree, ice, and glacier",
        description: "You wake around midnight to hot tea and biscuits, then begin the climb under a canopy of stars. The trail zigzags up steep scree slopes toward Stella Point (5,756m) on the crater rim — the most mentally and physically demanding section. As the sky begins to lighten, the glaciers glow pink and gold. From Stella Point, it's a 45-minute walk along the crater rim to Uhuru Peak — the Roof of Africa at 5,895m. After celebrating and photos, you descend to Mweka Camp for a well-earned rest.",
      },
      {
        day: 7,
        title: "Mweka Camp to Mweka Gate",
        elevation: "3,068m to 1,630m",
        distance: "10 km",
        time: "3-4 hours",
        terrain: "Rainforest",
        description: "Your final morning on the mountain. You descend through the cloud forest, retracing the journey from bare rock back to lush greenery. The air thickens, the temperature warms, and birdsong returns. At Mweka Gate, your crew will be waiting with celebration songs and your summit certificates. A transfer takes you back to your hotel in Moshi for a hot shower, a cold drink, and the deep satisfaction of having stood on Africa's highest point.",
      },
    ],
    highlights: [
      "Most scenic route",
      "Excellent acclimatization profile",
      "Diverse landscapes and vegetation zones",
      "High summit success rate",
    ],
  },
  {
    name: "Lemosho",
    nickname: "The Wilderness Route",
    durations: [{ days: "8 Days", price: "From $2,340" }],
    difficulty: "Moderate to Challenging",
    scenery: 5,
    description:
      "High success rate and gradual acclimatization. Ideal for serious climbers wanting the best summit chance.",
    itinerary: [
      "Hotel to Lemosho Gate – Mti Mkubwa Camp",
      "Mti Mkubwa Camp – Shira 1 Camp",
      "Shira 1 Camp – Shira 2 Camp",
      "Shira 2 Camp – Lava Tower (acclimatization & lunch) – Barranco Camp",
      "Barranco Camp – Karanga Camp",
      "Karanga Camp – Barafu Camp",
      "Summit (from Barafu Camp) – Mweka Camp",
      "Mweka Camp – Mweka Gate (to hotel)",
    ],
    detailedItinerary: [
      {
        day: 1,
        title: "Londorossi Gate to Mti Mkubwa Camp",
        elevation: "2,100m to 2,750m",
        distance: "6 km",
        time: "3-4 hours",
        terrain: "Rainforest",
        description: "After a scenic drive along the western slopes of Kilimanjaro, you'll register at Londorossi Gate and continue to the Lemosho trailhead. The hike begins through pristine montane rainforest — one of the quietest and most untouched approaches on the mountain. Blue monkeys dart through the canopy above, and the forest floor is carpeted in ferns. The gentle start is perfect for easing into mountain life.",
      },
      {
        day: 2,
        title: "Mti Mkubwa Camp to Shira 1 Camp",
        elevation: "2,750m to 3,500m",
        distance: "8 km",
        time: "5-7 hours",
        terrain: "Moorland & heath",
        description: "You climb out of the rainforest into the heather zone, where the landscape transforms dramatically. Giant heather gives way to open moorland with sweeping views of the western breach and the Shira Plateau. The going is steady, and you'll feel the air beginning to thin. Camp is set on the edge of the plateau — a vast, ancient caldera that feels like walking on the roof of the world.",
      },
      {
        day: 3,
        title: "Shira 1 Camp to Shira 2 Camp",
        elevation: "3,500m to 3,840m",
        distance: "6 km",
        time: "4-5 hours",
        terrain: "Plateau moorland",
        description: "A gentle traverse across the Shira Plateau — one of Kilimanjaro's three volcanic cones. The terrain is open, flat, and otherworldly, with the summit of Kibo looming ahead. You may spot eland, the world's largest antelope, grazing on the plateau. This easy day is designed for acclimatization, giving your body time to adjust before the bigger days ahead.",
      },
      {
        day: 4,
        title: "Shira 2 Camp to Lava Tower to Barranco Camp",
        elevation: "3,840m to 4,630m, descend to 3,960m",
        distance: "10 km",
        time: "6-8 hours",
        terrain: "Alpine desert",
        description: "The critical acclimatization day. You ascend to the striking Lava Tower at 4,630m — a colossal volcanic plug rising from the barren landscape. Lunch is served in its shadow before a rewarding descent to Barranco Camp. By climbing high and sleeping low, your body adapts more effectively. The Barranco Valley is spectacular, with giant groundsels and lobelias dotting the otherworldly terrain.",
      },
      {
        day: 5,
        title: "Barranco Camp to Karanga Camp",
        elevation: "3,960m to 3,995m",
        distance: "5 km",
        time: "4-5 hours",
        terrain: "Rocky scramble & valley",
        description: "An exhilarating start as you tackle the Barranco Wall — a fun, non-technical scramble that feels like an adventure playground at altitude. The views from the top are staggering. The trail then undulates through a series of valleys, crossing streams and rocky terrain before arriving at Karanga Camp. Take time to enjoy the views of the southern ice fields catching the afternoon light.",
      },
      {
        day: 6,
        title: "Karanga Camp to Barafu Camp",
        elevation: "3,995m to 4,673m",
        distance: "4 km",
        time: "3-4 hours",
        terrain: "Barren alpine desert",
        description: "A deliberately short day to conserve energy. The landscape is stark and beautiful — bare rock, thin air, and vast sky. You'll arrive at Barafu base camp by lunchtime, giving you the entire afternoon to rest, eat well, and mentally prepare for the summit attempt. Your guides will brief you on the night ahead. Early dinner, then try to sleep before the midnight wake-up call.",
      },
      {
        day: 7,
        title: "Summit Day — Uhuru Peak to Mweka Camp",
        elevation: "4,673m to 5,895m, descend to 3,068m",
        distance: "13 km",
        time: "12-16 hours",
        terrain: "Scree, ice, and glacier",
        description: "The pinnacle of your journey. Rising at midnight, you climb by headlamp through the darkness, each step bringing you closer to the Roof of Africa. The cold is intense, but your crew keeps you motivated with encouragement and hot drinks. Reaching Stella Point at dawn is deeply emotional — the glaciers shimmer in the first light. The final walk to Uhuru Peak (5,895m) is triumphant. After celebrations and photos, a long descent brings you to Mweka Camp.",
      },
      {
        day: 8,
        title: "Mweka Camp to Mweka Gate",
        elevation: "3,068m to 1,630m",
        distance: "10 km",
        time: "3-4 hours",
        terrain: "Rainforest",
        description: "A joyful descent back to civilization through lush rainforest. The crew will sing traditional celebration songs as you walk, and the mood is electric — you've done it. At Mweka Gate, collect your summit certificates, tip your incredible crew, and say your goodbyes. Transfer back to your hotel to relive every moment over a well-deserved meal.",
      },
    ],
    highlights: [
      "Remote and uncrowded start",
      "Best acclimatization profile",
      "Stunning panoramic views",
      "Highest success rate",
    ],
  },
  {
    name: "Marangu",
    nickname: "The Coca-Cola Route",
    durations: [
      { days: "6 Days", price: "From $1,810" },
      { days: "5 Days", price: "From $1,750" },
    ],
    difficulty: "Moderate",
    scenery: 3,
    description:
      "The only route with hut accommodation. A comfort-focused option with a gradual ascent and cozy sleeping arrangements.",
    itinerary: [
      "Marangu Gate – Mandara Hut",
      "Mandara – Horombo Hut",
      "Acclimatization Day",
      "Horombo – Kibo Hut",
      "Summit – Horombo",
      "Marangu Gate",
    ],
    detailedItinerary: [
      {
        day: 1,
        title: "Marangu Gate to Mandara Hut",
        elevation: "1,860m to 2,700m",
        distance: "8 km",
        time: "3-5 hours",
        terrain: "Rainforest",
        description: "The classic Kilimanjaro experience begins at Marangu Gate. The well-maintained trail leads through dense montane rainforest, rich with birdlife and the occasional troop of blue monkeys. Unlike other routes, you'll sleep in comfortable wooden huts with bunk beds and mattresses. Mandara Hut is a cozy cluster of A-frame cabins surrounded by forest — a welcoming introduction to life on the mountain.",
      },
      {
        day: 2,
        title: "Mandara Hut to Horombo Hut",
        elevation: "2,700m to 3,720m",
        distance: "11 km",
        time: "5-7 hours",
        terrain: "Moorland",
        description: "Leaving the forest canopy behind, the trail opens into rolling moorland with spectacular views. On clear mornings, both Kibo and Mawenzi peaks are visible ahead — a sight that takes your breath away. The heather and grasses give way to giant lobelias and groundsels, plants that look like they belong on another planet. Horombo Hut is the largest camp on the mountain with stunning sunset views.",
      },
      {
        day: 3,
        title: "Acclimatization Day at Horombo",
        elevation: "3,720m (day hike to 4,200m)",
        distance: "Optional hike",
        time: "3-4 hours",
        terrain: "Alpine desert",
        description: "A rest day designed to help your body adjust to the altitude — crucial for summit success. Most climbers take an optional hike toward Mawenzi Hut at 4,200m, getting a close-up view of Mawenzi's dramatic spires before descending back. The rest of the day is for relaxation, card games, journaling, and enjoying the mountain atmosphere. Your guides will monitor your health and acclimatization progress.",
      },
      {
        day: 4,
        title: "Horombo Hut to Kibo Hut",
        elevation: "3,720m to 4,703m",
        distance: "10 km",
        time: "5-7 hours",
        terrain: "Alpine desert",
        description: "The landscape turns stark and lunar as you cross \"the saddle\" — the vast, barren plateau between Mawenzi and Kibo peaks. Very little grows here, and the wind can whip across the open terrain. Kibo Hut sits at the base of the summit cone, a stone building that serves as your launch point for the final push. Early dinner, early bed — you'll need every minute of rest.",
      },
      {
        day: 5,
        title: "Summit Day — Uhuru Peak, descend to Horombo Hut",
        elevation: "4,703m to 5,895m, descend to 3,720m",
        distance: "21 km",
        time: "14-18 hours",
        terrain: "Scree, ice, and glacier",
        description: "The alarm sounds at midnight. Dressed in every warm layer you own, you begin the steep climb up volcanic scree by headlamp. The zigzagging trail to Gilman's Point (5,681m) on the crater rim is relentless but achievable — one step at a time. From Gilman's, traverse the rim past glaciers to Uhuru Peak at 5,895m. Watch the sunrise from the top of Africa. The descent is long — all the way back to Horombo Hut — but you'll be walking on air.",
      },
      {
        day: 6,
        title: "Horombo Hut to Marangu Gate",
        elevation: "3,720m to 1,860m",
        distance: "19 km",
        time: "5-7 hours",
        terrain: "Moorland & rainforest",
        description: "Your final descent passes quickly as you retrace your steps through moorland and back into the welcoming rainforest. The rich, oxygen-filled air feels incredible after days at altitude. At Marangu Gate, your crew will celebrate with songs and dancing. Collect your summit certificates, share grateful goodbyes, and transfer back to your hotel — a Kilimanjaro summiteer.",
      },
    ],
    highlights: [
      "Hut accommodation (no camping)",
      "Gradual ascent profile",
      "Shortest route option available",
      "Good for beginners with moderate fitness",
    ],
  },
  {
    name: "Rongai",
    nickname: "The Northern Approach",
    durations: [{ days: "7 Days", price: "From $2,440" }],
    difficulty: "Moderate",
    scenery: 4,
    description:
      "Northern approach near the Kenya border. Quieter and less crowded route with a gentle gradient ascent.",
    itinerary: [
      "Hotel to Rongai Gate – Simba Camp",
      "Simba Camp – Second Cave Camp",
      "Second Cave Camp – Kikelewa Camp",
      "Kikelewa Camp – Mawenzi Turn Camp",
      "Mawenzi Camp – Kibo Camp",
      "Summit (from Kibo Camp) – Horombo Camp",
      "Horombo Camp – Marangu Gate (to hotel)",
    ],
    detailedItinerary: [
      {
        day: 1,
        title: "Rongai Gate to Simba Camp",
        elevation: "1,950m to 2,600m",
        distance: "8 km",
        time: "3-4 hours",
        terrain: "Cultivated land & pine forest",
        description: "A scenic drive along the northern slopes of Kilimanjaro passes through rural villages and farmland, offering a glimpse of local Chagga life. The trail from Rongai Gate passes through planted pine forest before entering natural montane forest. The northern side of the mountain is drier and less visited, giving you a sense of true wilderness. Simba Camp (\"lion\" in Swahili) sits at the edge of the forest with views toward Kenya.",
      },
      {
        day: 2,
        title: "Simba Camp to Second Cave Camp",
        elevation: "2,600m to 3,450m",
        distance: "8 km",
        time: "5-6 hours",
        terrain: "Heath & moorland",
        description: "The trail climbs through heather and moorland, with the terrain opening up to reveal the drier, wilder northern slopes. You'll pass First Cave — a shallow overhanging rock that once served as a shelter for early climbers — before continuing to Second Cave Camp. The views across the Kenyan plains are vast and peaceful. Keep an eye out for white-necked ravens riding the thermals above.",
      },
      {
        day: 3,
        title: "Second Cave Camp to Kikelewa Camp",
        elevation: "3,450m to 3,600m",
        distance: "6 km",
        time: "3-4 hours",
        terrain: "Moorland",
        description: "A gentle day winding through open moorland dotted with giant heather and tussock grass. The route contours around the mountain's northern flank, offering unique perspectives of Mawenzi's jagged peaks that most climbers never see. Kikelewa Camp is nestled in a sheltered valley — a quiet, beautiful spot to spend the evening watching the stars appear one by one in the thin, clear air.",
      },
      {
        day: 4,
        title: "Kikelewa Camp to Mawenzi Tarn Camp",
        elevation: "3,600m to 4,330m",
        distance: "5 km",
        time: "4-5 hours",
        terrain: "Rocky alpine terrain",
        description: "A steeper climb today as you ascend to Mawenzi Tarn — a stunning alpine lake sitting beneath the dramatic spires and buttresses of Mawenzi peak. The landscape is raw and rugged, with volcanic rock formations and sparse vegetation. Camp is perched on the edge of the tarn with Mawenzi's cathedral-like pinnacles looming directly overhead — one of the most spectacular campsites on Kilimanjaro.",
      },
      {
        day: 5,
        title: "Mawenzi Tarn Camp to Kibo Camp",
        elevation: "4,330m to 4,703m",
        distance: "8 km",
        time: "5-6 hours",
        terrain: "Alpine desert",
        description: "You cross \"the saddle\" — the high-altitude desert connecting Mawenzi and Kibo. This lunar landscape is one of the most surreal environments on Earth: barren rock, thin air, and endless sky. The walking is relatively flat but the altitude makes every step count. Kibo Camp sits at the base of the summit cone. Rest, eat well, and prepare for midnight.",
      },
      {
        day: 6,
        title: "Summit Day — Uhuru Peak, descend to Horombo Hut",
        elevation: "4,703m to 5,895m, descend to 3,720m",
        distance: "21 km",
        time: "14-18 hours",
        terrain: "Scree, ice, and glacier",
        description: "The midnight ascent up the summit cone is grueling and glorious. Switchbacking up loose scree by headlamp, you climb toward Gilman's Point on the crater rim. The stars overhead are impossibly bright. As dawn breaks, you traverse past ancient glaciers to Uhuru Peak — the highest point in Africa. The views stretch across the continent. After summit photos, descend via the Marangu route to Horombo Hut for the night.",
      },
      {
        day: 7,
        title: "Horombo Hut to Marangu Gate",
        elevation: "3,720m to 1,860m",
        distance: "19 km",
        time: "5-7 hours",
        terrain: "Moorland & rainforest",
        description: "The final descent takes you down through zones you didn't climb through — the southern moorland and rainforest — offering a completely new perspective. The rich, thick forest air is a joy after days of thin mountain atmosphere. At Marangu Gate, celebrations await with singing, certificates, and the warm glow of achievement. Transfer back to your hotel as a Kilimanjaro summiteer.",
      },
    ],
    highlights: [
      "Least crowded route",
      "Gentle gradient ascent",
      "Unique northern wilderness views",
      "Great for those seeking solitude",
    ],
  },
  {
    name: "Umbwe",
    nickname: "The Steep Route",
    durations: [{ days: "6 Days", price: "From $2,197" }],
    difficulty: "Very Challenging",
    scenery: 4,
    description:
      "Challenging and steep — recommended for experienced trekkers. Fast ascent with dramatic landscapes.",
    itinerary: [
      "Hotel to Umbwe Gate – Umbwe Camp",
      "Umbwe Camp – Barranco Camp",
      "Barranco Camp – Karanga Camp",
      "Karanga Camp – Barafu Camp",
      "Summit (from Barafu Camp) – Mweka Camp",
      "Mweka Camp – Mweka Gate (to hotel)",
    ],
    detailedItinerary: [
      {
        day: 1,
        title: "Umbwe Gate to Umbwe Camp",
        elevation: "1,700m to 2,940m",
        distance: "10 km",
        time: "5-6 hours",
        terrain: "Dense rainforest",
        description: "The Umbwe route wastes no time. From the gate, the trail plunges into thick, primeval rainforest and immediately begins climbing steeply along a narrow ridge between two river valleys. Exposed tree roots form natural staircases, and the forest is darker and denser than on other routes. It's demanding from the start, but the sense of wild isolation is unmatched. You'll feel like an explorer discovering the mountain for the first time.",
      },
      {
        day: 2,
        title: "Umbwe Camp to Barranco Camp",
        elevation: "2,940m to 3,960m",
        distance: "6 km",
        time: "5-7 hours",
        terrain: "Steep moorland",
        description: "Another steep day as you push through the heath zone and into the moorland. The gradient is relentless, and you gain over 1,000m in elevation. But the rewards are immense — the views open up dramatically, and you'll see few if any other climbers. The route follows a ridge with drop-offs on either side, adding to the sense of adventure. Barranco Camp feels like a well-earned oasis beneath the towering Barranco Wall.",
      },
      {
        day: 3,
        title: "Barranco Camp to Karanga Camp",
        elevation: "3,960m to 3,995m",
        distance: "5 km",
        time: "4-5 hours",
        terrain: "Rocky scramble & valley",
        description: "You join the Machame route climbers for the thrilling scramble up the Barranco Wall. After the intensity of the previous days, this feels almost playful — using your hands to pull yourself up rock faces with stunning drops below. From the top, the trail winds through valleys to Karanga Camp. The southern glaciers and ice fields are visible above, gleaming in the sunlight.",
      },
      {
        day: 4,
        title: "Karanga Camp to Barafu Camp",
        elevation: "3,995m to 4,673m",
        distance: "4 km",
        time: "3-4 hours",
        terrain: "Barren alpine desert",
        description: "A short but significant ascent to Barafu base camp. The landscape is stripped bare — just rock, sky, and the summit above. Use the afternoon to rest deeply, eat well, and prepare for the midnight push. Your guides will check your health and brief you on summit night procedures. The sunset from Barafu is extraordinary — a sea of clouds below with Mawenzi's silhouette piercing the horizon.",
      },
      {
        day: 5,
        title: "Summit Day — Uhuru Peak to Mweka Camp",
        elevation: "4,673m to 5,895m, descend to 3,068m",
        distance: "13 km",
        time: "12-16 hours",
        terrain: "Scree, ice, and glacier",
        description: "Having trained hard and climbed the steepest route on the mountain, you're as ready as you'll ever be. The midnight ascent is a test of everything you have — physical strength, mental resilience, and raw determination. But standing on Uhuru Peak as the sun rises over Africa, every difficult step is vindicated. You've conquered Kilimanjaro via its toughest route. The long descent to Mweka Camp passes in a euphoric blur.",
      },
      {
        day: 6,
        title: "Mweka Camp to Mweka Gate",
        elevation: "3,068m to 1,630m",
        distance: "10 km",
        time: "3-4 hours",
        terrain: "Rainforest",
        description: "The final descent through rainforest is gentle and celebratory. The thick air feels luxurious in your lungs. Your crew walks with you, sharing stories and laughter. At Mweka Gate, receive your summit certificates and say farewell to the team that made it possible. Transfer to your hotel with a story few can tell — you climbed Kilimanjaro the hard way.",
      },
    ],
    highlights: [
      "Most challenging and rewarding",
      "Steep and direct ascent",
      "Very few other climbers",
      "Best for experienced trekkers",
    ],
  },
  {
    name: "Londorossi",
    nickname: "The Western Approach",
    durations: [{ days: "7 Days", price: "From $2,200" }],
    difficulty: "Moderate to Challenging",
    scenery: 5,
    description:
      "Remote western approach with excellent scenery. Gradual ascent through rainforest and Shira Plateau, joining the Machame route before summit. High success rate and scenic diversity.",
    itinerary: [
      "Hotel to Londorossi Gate – Shira 1 Camp",
      "Shira 1 Camp – Shira 2 Camp",
      "Shira 2 Camp – Lava Tower (acclimatization & lunch) – Barranco Camp",
      "Barranco Camp – Karanga Camp",
      "Karanga Camp – Barafu Camp",
      "Summit (from Barafu Camp) – Mweka Camp",
      "Mweka Camp – Mweka Gate (to hotel)",
    ],
    detailedItinerary: [
      {
        day: 1,
        title: "Londorossi Gate to Shira 1 Camp",
        elevation: "2,250m to 3,500m",
        distance: "8 km",
        time: "4-5 hours",
        terrain: "Rainforest & heath",
        description: "The journey begins with a drive to the remote Londorossi Gate on Kilimanjaro's western face. After registration, you may drive or hike through the lower rainforest zone to reach the trailhead. The climb passes through mossy forest that gradually thins into heather moorland. You'll arrive at Shira 1 Camp on the western edge of the ancient Shira Plateau — a vast caldera with sweeping sunset views that few Kilimanjaro climbers ever witness.",
      },
      {
        day: 2,
        title: "Shira 1 Camp to Shira 2 Camp",
        elevation: "3,500m to 3,840m",
        distance: "7 km",
        time: "4-5 hours",
        terrain: "Plateau moorland",
        description: "A scenic traverse across the Shira Plateau. The terrain is gently rolling, covered in tussock grass and wild flowers. Kibo peak dominates the eastern horizon, growing larger with every step. This is one of the most photogenic sections of any Kilimanjaro route — wide open skies, volcanic rock formations, and an extraordinary sense of space and solitude. A perfect acclimatization day.",
      },
      {
        day: 3,
        title: "Shira 2 Camp to Lava Tower to Barranco Camp",
        elevation: "3,840m to 4,630m, descend to 3,960m",
        distance: "10 km",
        time: "6-8 hours",
        terrain: "Alpine desert",
        description: "The key acclimatization day as you ascend to the imposing Lava Tower at 4,630m. This massive volcanic rock pillar marks your high point before you descend into the Barranco Valley. The \"climb high, sleep low\" strategy is essential for summit success — and this day delivers it perfectly. The descent into Barranco reveals dramatic scenery: giant groundsels, lobelia plants, and the Great Barranco Wall ahead.",
      },
      {
        day: 4,
        title: "Barranco Camp to Karanga Camp",
        elevation: "3,960m to 3,995m",
        distance: "5 km",
        time: "4-5 hours",
        terrain: "Rocky scramble & valley",
        description: "The Barranco Wall awaits — a thrilling, hands-on scramble that's more exhilarating than difficult. Your guides navigate the best line up the rock face, and the exposure is exciting without being dangerous. From the top, panoramic views of the southern glaciers reward your effort. The trail then dips through valleys to Karanga Camp, where you'll spend a peaceful afternoon watching clouds swirl around the summit above.",
      },
      {
        day: 5,
        title: "Karanga Camp to Barafu Camp",
        elevation: "3,995m to 4,673m",
        distance: "4 km",
        time: "3-4 hours",
        terrain: "Barren alpine desert",
        description: "A short climb through increasingly barren terrain to Barafu base camp. The world is reduced to rock, wind, and sky. Arrive by lunchtime, rest through the afternoon, and eat a hearty early dinner. Your guide will brief the group on summit night logistics. Try to sleep — though anticipation often makes this the hardest night to rest. Tomorrow, you reach the top of Africa.",
      },
      {
        day: 6,
        title: "Summit Day — Uhuru Peak to Mweka Camp",
        elevation: "4,673m to 5,895m, descend to 3,068m",
        distance: "13 km",
        time: "12-16 hours",
        terrain: "Scree, ice, and glacier",
        description: "Midnight start under a brilliant star-filled sky. The steep, switchbacking climb up scree is a test of will and endurance. Your guides set a steady, manageable pace — \"pole pole\" (slowly, slowly) is the mantra. Reaching the crater rim at Stella Point as dawn breaks is overwhelmingly beautiful. The final walk along the rim to Uhuru Peak at 5,895m is the culmination of everything. Celebrate, take in the view across Africa, then begin the long descent to Mweka Camp.",
      },
      {
        day: 7,
        title: "Mweka Camp to Mweka Gate",
        elevation: "3,068m to 1,630m",
        distance: "10 km",
        time: "3-4 hours",
        terrain: "Rainforest",
        description: "The final morning on the mountain. Descend through cloud forest back to the warmth and richness of the lowlands. Your porters and guides will sing celebration songs along the trail. At Mweka Gate, receive your hard-earned summit certificates and share heartfelt goodbyes with the crew who made this journey possible. Transfer to your hotel and bask in the glow of an incredible achievement.",
      },
    ],
    highlights: [
      "Remote western starting point",
      "Excellent scenery and acclimatization",
      "Low traffic",
      "Similar to Lemosho experience",
    ],
  },
];

export const SAFARI_PARKS = [
  {
    name: "Serengeti National Park",
    description:
      "Home to the Great Migration — witness millions of wildebeest and zebras crossing the plains in one of nature's greatest spectacles.",
    highlights: ["Great Migration", "Big Five", "Endless plains", "Hot air balloon safaris"],
  },
  {
    name: "Ngorongoro Crater",
    description:
      "The world's largest intact volcanic caldera, teeming with wildlife in a breathtaking natural amphitheater.",
    highlights: ["UNESCO World Heritage Site", "Dense wildlife concentration", "Flamingo-lined lakes", "Maasai culture"],
  },
  {
    name: "Tarangire National Park",
    description:
      "Famous for its massive elephant herds and iconic baobab trees, offering an intimate safari experience away from the crowds.",
    highlights: ["Large elephant herds", "Ancient baobab trees", "Bird watching paradise", "Less crowded"],
  },
  {
    name: "Lake Manyara National Park",
    description:
      "A compact gem known for tree-climbing lions and diverse birdlife along the shores of a beautiful soda lake.",
    highlights: ["Tree-climbing lions", "Flamingo flocks", "Diverse ecosystems", "Scenic lake views"],
  },
  {
    name: "Mkomazi National Park",
    description:
      "A hidden treasure bordering Kenya, home to rare African wild dogs, black rhinos, and stunning semi-arid landscapes.",
    highlights: ["Black rhinos", "African wild dogs", "Remote wilderness", "Scenic semi-arid terrain"],
  },
];

export const TESTIMONIALS = [
  {
    name: "Sarah Johnson",
    location: "United States",
    text: "Climbing Kilimanjaro with True Venture was the experience of a lifetime. Our guide Abu was incredible — knowledgeable, patient, and so encouraging. We reached the summit at sunrise and I cried tears of joy.",
    tour: "Kilimanjaro — Lemosho Route",
    rating: 5,
  },
  {
    name: "Marcus Weber",
    location: "Germany",
    text: "The safari exceeded all expectations. Seeing the Great Migration in the Serengeti was something I'll never forget. The team planned everything perfectly and our guide spotted animals we would have never seen on our own.",
    tour: "Wildlife Safari — 5 Days",
    rating: 5,
  },
  {
    name: "Yuki Tanaka",
    location: "Japan",
    text: "The cultural experience tour was so authentic and respectful. We visited a Maasai village, learned about their traditions, and shared a meal together. It felt like a genuine connection, not a tourist show.",
    tour: "Cultural Experience",
    rating: 5,
  },
  {
    name: "Emma & James Clarke",
    location: "United Kingdom",
    text: "We did the Machame route for our honeymoon adventure and it was magical. The crew was amazing — delicious food at altitude, warm smiles every day, and professional safety standards throughout.",
    tour: "Kilimanjaro — Machame Route",
    rating: 5,
  },
];

export const WHY_CHOOSE_US = [
  {
    title: "Local Expert Guides",
    description:
      "Our certified, born-and-raised Tanzanian guides bring deep knowledge of altitude management, acclimatization, and mountain safety.",
    icon: "compass",
  },
  {
    title: "Safety First",
    description:
      "Daily health checks, oxygen monitoring, emergency oxygen cylinders, first aid kits, proper acclimatization schedules, and clear evacuation procedures.",
    icon: "shield",
  },
  {
    title: "Ethical Porter Treatment",
    description:
      "Our founder's experience as a former porter ensures fair wages, proper meals, reasonable load limits, and respectful working conditions for all crew.",
    icon: "heart",
  },
  {
    title: "All-Inclusive Packages",
    description:
      "Airport transfers, hotel accommodation, park fees, quality equipment, nutritious meals, professional guides — everything taken care of.",
    icon: "package",
  },
  {
    title: "Community Impact",
    description:
      "A portion of our profits supports education initiatives, health awareness, and environmental conservation in local communities.",
    icon: "users",
  },
  {
    title: "Founded by Experience",
    description:
      "Our founder started as a porter and became a professional guide. We understand the mountain from every level — physically, emotionally, and professionally.",
    icon: "trophy",
  },
];

export const TEAM_MEMBERS = [
  {
    name: "Abdallah Athumani (Abu)",
    role: "Founder & Professional Mountain Guide",
    bio: "Abu began his journey on Kilimanjaro as a porter before becoming a certified professional mountain guide. His years of experience shaped the company's core values: safety, respect, hard work, and integrity.",
    image: "/images/guide-client.jpg",
  },
];

export const MOUNTAIN_CREW = [
  "Senior Mountain Guide",
  "Assistant Guide",
  "Professional Mountain Cook",
  "Camp Waiter",
  "Dedicated Porters",
];

export const SAFARI_CREW = [
  "Professional Safari Driver Guide",
  "Wildlife Specialist Guide",
];

export const PACKAGE_INCLUDES = [
  "Airport pick up and drop off",
  "2-night hotel accommodation in Moshi/Arusha (before and after trek) on full board basis",
  "Quality, waterproof, four-season mountain sleeping tent",
  "Quality mess tents with table and chairs",
  "Professional, experienced, English-speaking mountain guides",
  "All Tanzanian National Park fees",
  "All hot meals prepared by our cook while on the mountain",
  "Portable toilet tent",
  "Fair wages for guides, porters, and cook as approved by KINAPA",
  "Oxygen tank and pulse oximeter for health and safety",
  "Hot drinks at every meal",
  "Water provided on climb (mineral water day 1, boiled water daily)",
  "Certificate of achievement after the climb",
];

export const PACKAGE_EXCLUDES = [
  "International and domestic flights",
  "Tanzanian entry visa fees",
  "Travel insurance (mandatory for trekkers)",
  "Sleeping bags and personal trekking gear (available for rent)",
  "Tips for guides, porters, and cook",
  "Personal expenses (drinks, snacks, laundry, souvenirs)",
  "Additional accommodation before or after the trek (unless included in package)",
];

export const TOUR_INTERESTS = [
  "Kilimanjaro — Machame Route",
  "Kilimanjaro — Lemosho Route",
  "Kilimanjaro — Marangu Route",
  "Kilimanjaro — Rongai Route",
  "Kilimanjaro — Umbwe Route",
  "Kilimanjaro — Londorossi Route",
  "Mount Meru",
  "Wildlife Safari",
  "Zanzibar Holiday",
  "Cultural Experience",
  "Kilimanjaro + Safari Combo",
  "Custom Trip",
];
